"""user posts

Revision ID: 01d3d335c5a5
Revises: 8c336f81ac72
Create Date: 2022-11-22 07:49:13.013837

"""

# revision identifiers, used by Alembic.
revision = '01d3d335c5a5'
down_revision = '8c336f81ac72'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
