"""initial migration


Revision ID: 278a2ff8b58b
Revises: 99051999910d
Create Date: 2022-11-15 18:31:55.854003

"""

# revision identifiers, used by Alembic.
revision = '278a2ff8b58b'
down_revision = '99051999910d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
