"""blog post migration

Revision ID: 30ccbb4f0fb7
Revises: 0c592aabccc8
Create Date: 2022-11-20 15:21:12.608484

"""

# revision identifiers, used by Alembic.
revision = '30ccbb4f0fb7'
down_revision = '0c592aabccc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamps', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_timestamps'), 'posts', ['timestamps'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamps'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
