"""posts migration

Revision ID: 313cd02faab9
Revises: 30ccbb4f0fb7
Create Date: 2022-11-21 18:05:24.018337

"""

# revision identifiers, used by Alembic.
revision = '313cd02faab9'
down_revision = '30ccbb4f0fb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
