"""rich text blogposts

Revision ID: 409d30ed3ea1
Revises: 01d3d335c5a5
Create Date: 2022-11-22 16:48:25.657621

"""

# revision identifiers, used by Alembic.
revision = '409d30ed3ea1'
down_revision = '01d3d335c5a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
