"""user post migration

Revision ID: 8c336f81ac72
Revises: 313cd02faab9
Create Date: 2022-11-21 19:12:52.476986

"""

# revision identifiers, used by Alembic.
revision = '8c336f81ac72'
down_revision = '313cd02faab9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_posts_timestamps', table_name='posts')
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.drop_column('posts', 'timestamps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamps', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.create_index('ix_posts_timestamps', 'posts', ['timestamps'], unique=False)
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
