"""Selenium migration

Revision ID: 9aaa6df1d21a
Revises: e9eb9567c9cf
Create Date: 2022-12-17 23:12:25.424425

"""

# revision identifiers, used by Alembic.
revision = '9aaa6df1d21a'
down_revision = 'e9eb9567c9cf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
