"""initial migration


Revision ID: a537cadbb0e9
Revises: ddfa63cb4e03
Create Date: 2022-11-18 18:28:51.287073

"""

# revision identifiers, used by Alembic.
revision = 'a537cadbb0e9'
down_revision = 'ddfa63cb4e03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
