"""initial migration

Revision ID: e3a683857d29
Revises: 77f6d85045e9
Create Date: 2022-11-11 09:57:41.103564

"""

# revision identifiers, used by Alembic.
revision = 'e3a683857d29'
down_revision = '77f6d85045e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
