"""followers migration

Revision ID: f2b1a8dc697c
Revises: cae2b3bcb2e2
Create Date: 2022-11-25 20:06:28.356661

"""

# revision identifiers, used by Alembic.
revision = 'f2b1a8dc697c'
down_revision = 'cae2b3bcb2e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
